modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="yio"
version="1.0.0"
displayName="Yank It Out"
credits="zsvan"
displayURL="https://discord.gg/Gg6hMm3UcG"
logoFile="logo.png"
authors="zsvan"
description="Pull arrows from your body."

[[dependencies.yio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




